#!/usr/bin/env python3
"""
Utility script to quickly run solution binary against an input file.
Requires Python 3.7 or higher.
Author: Abhabongse Janthong
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

DAY_EXTRACT_RE = re.compile(r"(?P<day>day\d{2})")


def main():
    args = get_program_args()
    input_file: pathlib.Path = args.input_file

    if not input_file.is_file():
        sys.exit("error: input file not found")
    matchobj = DAY_EXTRACT_RE.match(input_file.name)
    if not matchobj:
        sys.exit("error: input file name must begin with 'dayNN' (e.g. day01)")
    day = matchobj[1]

    subprocess.run(["cargo", "run", "--release", "--bin", day, input_file])


def get_program_args(args=None):
    parser = argparse.ArgumentParser(description="Quickly run solution binary against an input file")
    parser.add_argument('input_file', type=pathlib.Path, help="Path to input file")
    return parser.parse_args(args)


if __name__ == '__main__':
    main()
