# This workflow will perform static checking on rust source code, run tests against the build,
# and run linter (clippy) and formatter (rustfmt) to check source code quality.
name: Rust Check

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and Run Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rust build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy linter check
      run: cargo clippy --all -- -D warnings
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rust formatter check
      run: cargo fmt --all -- --check
